"""
Django settings for chiron_demo project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "1b_762p=(t97y-(y!@2pp5hzq*z)*va*e*akjuu_==#om4a8oe"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# attach to local version of chiron
sys.path.append("..")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "rest_framework",
    "crispy_forms",
    "chiron",
    "main",
    "ontologies",
    "patient_models",  # some django models for testing ETL from Django ORM sources
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "chiron.middleware.view_as_other_user.ViewAsOtherUser",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"  # other options is BigAutoField


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "chiron_demo"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"


CRISPY_TEMPLATE_PACK = "bootstrap4"

# CHIRON CONFIG

TEMPLATES[0]["OPTIONS"]["context_processors"].append("chiron.context_processors.chiron_globals")

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "demo.backends.ChironRemoteUserBackend",
    # "demo.backends.ChironRemoteUserBackend",  # if you have this
]
CHIRON_TREAT_ONTOLOGY_CONCEPTS_AS_TEXT = False

CHIRON_SITE_TITLE = "Chiron Test Project"
CHIRON_INFOBAR = "This is a small dummy database for testing"
CHIRON_INFOBAR_TYPE = "info"  # affects coloring of infobar, options: info, warning, danger
CHIRON_PROCESSOR_MODULES = ["chiron.processors", "chiron_config.processors"]
CHIRON_SHOW_ANALYSIS_VIEW = True
CHIRON_AGG_SUBJECT_COUNT_MIN_LIMIT = 5
CHIRON_USE_CACHES = False
CHIRON_DATABASE = "postgres"
CHIRON_SQL_ALCHEMY_CONNECTION_STRING = f"postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'postgres')}@{os.getenv('DB_HOST', 'localhost')}:5432/{os.getenv('DB_NAME', 'chiron_demo')}"
CHIRON_TREAT_ONTOLOGY_CONCEPTS_AS_TEXT = False

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login"

# include any custom settings for this instance
try:
    from .settings_custom import *  # noqa
except ImportError:
    pass
    
    
    
SESSION_COOKIE_SAMESITE = "Lax"  # or "None" if using HTTPS and cross-site
SESSION_COOKIE_SECURE = False    # True if using HTTPS in production

CSRF_TRUSTED_ORIGINS = ['http://localhost']
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
]


CHIRON_SOURCE_DATA_DIRECTORY = str(BASE_DIR / "chiron_config/data") + "/"